Reorder Fix
sge-network/sge pull request #260
Opened 2023-09-26 20:45 UTC by P-U-D-G-E

## Description

Changes the reordering logic 
When a bet is placed, if for any depositor is_fullfilled is being set as true, check if the depositor should be reordered. The depositor if eligible to be reordered should be reordered post placement of bet. Conditions for reordering -

- Exposure for other odds should be is_fullfilled = True
- If for any odd exposure for this depositor has is_fullfilled = False, recalculate the exposure if <=requeThreshold set is as is_fullfilled = True.

---

## Type of change

Please check the options that are relevant. This PR introduces

- [x] Patch: Bug fix (non-breaking change which fixes an existing issue)
- [ ] Minor: New feature (non-breaking change which adds new functionality)
- [ ] Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Features Description

- [ ] NA

---

## Test Cases

- [ ] NA

---

## Documentation

---

## Checklist:

- [ ] I have added change type (major|minor|patch) in the PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
---

2023-09-27 09:58 UTC, scorpioborn requested changes

2023-10-02 10:08 UTC, P-U-D-G-E commented on x/bet/keeper/wager.go
> +
it creates a cyclic dependency

2023-10-02 10:08 UTC, P-U-D-G-E commented on proto/sge/bet/ticket.proto
> +  repeated BetOdds odds = 4;
changed

2023-10-02 10:20 UTC, P-U-D-G-E commented on proto/sge/bet/ticket.proto
> +  repeated BetOdds odds = 4;
Changed

2023-10-02 10:21 UTC, P-U-D-G-E commented on x/bet/types/ticket.go
> +	if err := payload.ValidateOdds(*payload.SelectedOdds); err != nil {
was using the same function to validate all odds too, since all odds were changed to CompactOdds, the validate function is changed too . resolved

2023-10-02 10:54 UTC, 3eyedraga approved these changes

2023-10-02 11:04 UTC, merged